=== OlgaGv/EPAM_JavaWebDev_Course/Task4_XML/data/gems.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://www.example.com/gems"
        targetNamespace="http://www.example.com/gems"
        elementFormDefault="qualified">

    <element name="AbstractGem" type="tns:AbstractGem" abstract="true"/>

    <element name="Gems">
        <complexType mixed="true">
            <sequence>
                <element ref="tns:AbstractGem" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="AbstractGem" mixed="true">
        <sequence>
            <element name="name" type="string"/>
            <element name="preciousness" type="tns:Preciousness"/>
            <element name="weight" type="tns:Weight"/>
            <element name="gemArrival" type="date" default="01-01-2010"/>
        </sequence>
        <attribute name="origin" type="tns:Origin" default="OTHER"/>
        <attribute name="id" type="integer" use="required"/>

    </complexType>

    <element name="Emerald" substitutionGroup="tns:AbstractGem">
        <complexType mixed="true">
            <complexContent>
                <extension base="tns:AbstractGem">
                    <sequence>
                        <element name="color" type="string"/>
                        <element name="transparency" type="tns:Transparency"/>
                        <element name="amountofcuts" type="tns:amountOfCuts"/>
                    </sequence>
                </extension>
            </complexContent>

        </complexType>
    </element>

    <element name="Diamond" substitutionGroup="tns:AbstractGem">
        <complexType mixed="true">
            <complexContent>
                <extension base="tns:AbstractGem">
                    <sequence>
                        <element name="transparency" type="tns:Transparency"/>
                        <element name="amountofcuts" type="tns:amountOfCuts"/>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
    </element>

    <element name="Pearl" substitutionGroup="tns:AbstractGem">
        <complexType mixed="true">
            <complexContent>
                <extension base="tns:AbstractGem">
                    <sequence>
                        <element name="color" type="string"/>
                        <element name="luster" type="tns:Luster"/>
                    </sequence>
                </extension>
            </complexContent>
        </complexType>
    </element>

    <complexType name="Weight">
        <all>
            <element name="value" type="double"/>
            <element name="unit">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="KG"/>
                        <enumeration value="KARAT"/>
                    </restriction>
                </simpleType>
            </element>
        </all>
    </complexType>

    <simpleType name="Luster">
        <restriction base="string">
            <enumeration value="EXCELLENT"/>
            <enumeration value="VERY-GOOD"/>
            <enumeration value="GOOD"/>
            <enumeration value="BAD"/>
        </restriction>
    </simpleType>

    <simpleType name="amountOfCuts">
        <restriction base="integer">
            <minInclusive value="4"/>
            <maxInclusive value="15"/>
        </restriction>
    </simpleType>

    <simpleType name="Transparency">
        <restriction base="double">
            <minInclusive value="0"/>
            <maxInclusive value="100"/>
        </restriction>
    </simpleType>

    <simpleType name="Preciousness">
        <restriction base="string">
            <enumeration value="PRECIOUS"/>
            <enumeration value="SEMI-PRECIOUS"/>
        </restriction>
    </simpleType>

    <simpleType name="Origin">
        <restriction base="string">
            <enumeration value="AFRICA"/>
            <enumeration value="ASIA"/>
            <enumeration value="ANTARCTICA"/>
            <enumeration value="SOUTH AMERICA"/>
            <enumeration value="NORTH AMERICA"/>
            <enumeration value="EUROPE"/>
            <enumeration value="AUSTRALIA"/>
            <enumeration value="OTHER"/>
        </restriction>
    </simpleType>
</schema>

=== OlgaGv/EPAM_JavaWebDev_Course/Task4_XML/data/gems.xml
<!--http://www.diamondse.info/diamonds-price-index.asp-->
<Gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.example.com/gems"
      xsi:schemaLocation="http://www.example.com/gems gems.xsd">

    <Diamond origin="ASIA" id="42">
        <name>Red Velvet</name>
        <preciousness>SEMIPRECIOUS</preciousness>
        <weight>
            <value>40.4</value>
            <unit>KG</unit>
        </weight>
        <gemArrival>2019-09-09</gemArrival>
        <transparency>50</transparency>
        <amountofcuts>6</amountofcuts>
    </Diamond>

    <Emerald id="1" origin="ANTARCTICA">
        <name>Princess</name>
        <preciousness>PRECIOUS</preciousness>
        <weight>
            <unit>KARAT</unit>
            <value>4</value>
        </weight>
        <gemArrival>2019-09-09</gemArrival>
        <color>red</color>
        <transparency>80</transparency>
        <amountofcuts>5</amountofcuts>
    </Emerald>

    <Diamond origin="NORTH_AMERICA" id="32">
        <name>Purple Crystal</name>
        <preciousness>SEMIPRECIOUS</preciousness>
        <weight>
            <value>4</value>
            <unit>KG</unit>
        </weight>
        <gemArrival>1971-09-09</gemArrival>
        <transparency>50</transparency>
        <amountofcuts>7</amountofcuts>
    </Diamond>

    <Emerald id="80" origin="ANTARCTICA">
        <name>Greeny</name>
        <preciousness>SEMIPRECIOUS</preciousness>
        <weight>
            <unit>KG</unit>
            <value>0.70</value>
        </weight>
        <gemArrival>2019-01-09</gemArrival>
        <color>Green</color>
        <transparency>8</transparency>
        <amountofcuts>9</amountofcuts>
    </Emerald>

    <Pearl origin="ASIA" id="3">
        <name>Round Whites</name>
        <preciousness>PRECIOUS</preciousness>
        <weight>
            <value>23</value>
            <unit>KARAT</unit>
        </weight>
        <gemArrival>2018-09-04</gemArrival>
        <color>Milky White</color>
        <luster>VERY-GOOD</luster>
    </Pearl>
    <Pearl origin="ASIA" id="981">
        <name>Moon Blue</name>
        <preciousness>SEMIPRECIOUS</preciousness>
        <weight>
            <value>0.11</value>
            <unit>KG</unit>
        </weight>
        <gemArrival>2011-09-04</gemArrival>
        <color>Milky Blue</color>
        <luster>GOOD</luster>
    </Pearl>
    <Pearl origin="AUSTRALIA" id="981">
        <name>Clear White</name>
        <preciousness>SEMIPRECIOUS</preciousness>
        <weight>
            <value>22</value>
            <unit>KARAT</unit>
        </weight>
        <gemArrival>2011-09-04</gemArrival>
        <color>White</color>
        <luster>GOOD</luster>
    </Pearl>

    <Diamond origin="OTHER" id="2">
        <name>Black Void</name>
        <preciousness>PRECIOUS</preciousness>
        <weight>
            <value>69</value>
            <unit>KG</unit>
        </weight>
        <gemArrival>2000-09-09</gemArrival>
        <transparency>0</transparency>
        <amountofcuts>7</amountofcuts>
    </Diamond>

    <Emerald id="1110" origin="ANTARCTICA">
        <name>Yellowy</name>
        <preciousness>SEMIPRECIOUS</preciousness>
        <weight>
            <unit>KARAT</unit>
            <value>100.0</value>
        </weight>
        <gemArrival>2019-01-09</gemArrival>
        <color>Green Yellowish</color>
        <transparency>99.9</transparency>
        <amountofcuts>5</amountofcuts>
    </Emerald>

    <Pearl origin="EUROPE" id="4443">
        <name>Quirky Brown</name>
        <preciousness>PRECIOUS</preciousness>
        <weight>
            <value>1</value>
            <unit>KARAT</unit>
        </weight>
        <gemArrival>2000-09-04</gemArrival>
        <color>Brown</color>
        <luster>BAD</luster>
    </Pearl>
    <Diamond origin="ANTARCTICA" id="562">
        <name>Greymane</name>
        <preciousness>PRECIOUS</preciousness>
        <weight>
            <value>11</value>
            <unit>KG</unit>
        </weight>
        <gemArrival>2100-09-09</gemArrival>
        <transparency>15</transparency>
        <amountofcuts>12</amountofcuts>
    </Diamond>

    <Emerald id="2018" origin="AFRICA">
        <name>Minecraft Emerald</name>
        <preciousness>SEMIPRECIOUS</preciousness>
        <weight>
            <unit>KARAT</unit>
            <value>100.0</value>
        </weight>
        <gemArrival>2010-01-09</gemArrival>
        <color>Green Bit</color>
        <transparency>99.9</transparency>
        <amountofcuts>5</amountofcuts>
    </Emerald>

    <Pearl origin="ANTARCTICA" id="411443">
        <name>Rainbow</name>
        <preciousness>PRECIOUS</preciousness>
        <weight>
            <value>71717</value>
            <unit>KARAT</unit>
        </weight>
        <gemArrival>2000-09-04</gemArrival>
        <color>Rainbow</color>
        <luster>VERY-GOOD</luster>
    </Pearl>
    <Diamond origin="ANTARCTICA" id="562">
        <name>Greymane</name>
        <preciousness>PRECIOUS</preciousness>
        <weight>
            <value>11</value>
            <unit>KG</unit>
        </weight>
        <gemArrival>2100-09-09</gemArrival>
        <transparency>15</transparency>
        <amountofcuts>12</amountofcuts>
    </Diamond>

    <Emerald id="2018" origin="AFRICA">
        <name>Red Emerald</name>
        <preciousness>SEMIPRECIOUS</preciousness>
        <weight>
            <unit>KARAT</unit>
            <value>100.0</value>
        </weight>
        <gemArrival>2010-01-09</gemArrival>
        <color>Green Bit</color>
        <transparency>99.9</transparency>
        <amountofcuts>5</amountofcuts>
    </Emerald>

    <Pearl origin="ANTARCTICA" id="411443">
        <name>Rainbow</name>
        <preciousness>PRECIOUS</preciousness>
        <weight>
            <value>71717</value>
            <unit>KARAT</unit>
        </weight>
        <gemArrival>2000-09-04</gemArrival>
        <color>Rainbow</color>
        <luster>VERY-GOOD</luster>
    </Pearl>
</Gems>
